const teamMapper = {
    ATL: "ATL",
    BOS: "BOS",
    BRK: "BKN",
    CHI: "CHI",
    CHO: "CHA",
    CLE: "CLE",
    DAL: "DAL",
    DEN: "DEN",
    DET: "DET",
    GSW: "GSW",
    HOU: "HOU",
    IND: "IND",
    LAC: "LAC",
    LAL: "LAL",
    MEM: "MEM",
    MIA: "MIA",
    MIL: "MIL",
    MIN: "MIN",
    NOP: "NOP",
    NYK: "NYK",
    OKC: "OKC",
    ORL: "ORL",
    PHI: "PHI",
    PHO: "PHX",
    POR: "POR",
    SAC: "SAC",
    SAS: "SAS",
    TOR: "TOR",
    UTA: "UTA",
    WAS: "WAS"
}

const name_mapper = {
    AtlantaHawks: "ATL",
    BostonCeltics: "BOS",
    BrooklynNets: "BKN",
    ChicagoBulls: "CHI",
    CharlotteHornets: "CHA",
    ClevelandCavaliers: "CLE",
    DallasMavericks: "DAL",
    DenverNuggets: "DEN",
    DetroitPistons: "DET",
    GoldenStateWarriors: "GSW",
    HoustonRockets: "HOU",
    IndianaPacers: "IND",
    LosAngelesClippers: "LAC",
    LosAngelesLakers: "LAL",
    MemphisGrizzlies: "MEM",
    MiamiHeat: "MIA",
    MilwaukeeBucks: "MIL",
    MinnesotaTimberwolves: "MIN",
    NewOrleansPelicans: "NOP",
    NewYorkKnicks: "NYK",
    OklahomaCityThunder: "OKC",
    OrlandoMagic: "ORL",
    Philadelphia76ers: "PHI",
    PhoenixSuns: "PHX",
    PortlandTrailBlazers: "POR",
    SacramentoKings: "SAC",
    SanAntonioSpurs: "SAS",
    TorontoRaptors: "TOR",
    UtahJazz: "UTA",
    WashingtonWizards: "WAS"
}

export { teamMapper, name_mapper}