const teamMapper = {
    ATL: "ATL",
    BOS: "BOS",
    BRK: "BKN",
    CHI: "CHI",
    CHO: "CHA",
    CLE: "CLE",
    DAL: "DAL",
    DEN: "DEN",
    DET: "DET",
    GSW: "GSW",
    HOU: "HOU",
    IND: "IND",
    LAC: "LAC",
    LAL: "LAL",
    MEM: "MEM",
    MIA: "MIA",
    MIL: "MIL",
    MIN: "MIN",
    NOP: "NOP",
    NYK: "NYK",
    OKC: "OKC",
    ORL: "ORL",
    PHI: "PHI",
    PHO: "PHX",
    POR: "POR",
    SAC: "SAC",
    SAS: "SAS",
    TOR: "TOR",
    UTA: "UTA",
    WAS: "WAS"
}

const name_mapper = {
    AtlantaHawks: "ATL",
    BostonCeltics: "BOS",
    BrooklynNets: "BKN",
    ChicagoBulls: "CHI",
    CharlotteHornets: "CHA",
    ClevelandCavaliers: "CLE",
    DallasMavericks: "DAL",
    DenverNuggets: "DEN",
    DetroitPistons: "DET",
    GoldenStateWarriors: "GSW",
    HoustonRockets: "HOU",
    IndianaPacers: "IND",
    LosAngelesClippers: "LAC",
    LosAngelesLakers: "LAL",
    MemphisGrizzlies: "MEM",
    MiamiHeat: "MIA",
    MilwaukeeBucks: "MIL",
    MinnesotaTimberwolves: "MIN",
    NewOrleansPelicans: "NOP",
    NewYorkKnicks: "NYK",
    OklahomaCityThunder: "OKC",
    OrlandoMagic: "ORL",
    Philadelphia76ers: "PHI",
    PhoenixSuns: "PHX",
    PortlandTrailBlazers: "POR",
    SacramentoKings: "SAC",
    SanAntonioSpurs: "SAS",
    TorontoRaptors: "TOR",
    UtahJazz: "UTA",
    WashingtonWizards: "WAS"
}

const team_names = {
    ATL: ['Atlanta Hawks', 'Hawks'],
    BOS: ['Boston Celtics', 'Celtics'],
    BRK: ['Brooklyn Nets', 'Nets'],
    CHI: ['Chicago Bulls', 'Bulls'],
    CHO: ['Charlotte Hornets', 'Hornets'],
    CLE: ['Cleveland Cavaliers', 'Cavaliers'],
    DAL: ['Dallas Mavericks', 'Mavericks'],
    DEN: ['Denver Nuggets', 'Nuggets'],
    DET: ['Detroit Pistons', 'Pistons'],
    GSW: ['Golden State Warriors', 'Warriors'],
    HOU: ['Houston Rockets', 'Rockets'],
    IND: ['Indiana Pacers', 'Pacers'],
    LAC: ['Los Angeles Clippers', 'Clippers'],
    LAL: ['Los Angeles Lakers', 'Lakers'],
    MEM: ['Memphis Grizzlies', 'Grizzlies'],
    MIA: ['Miami Heat', 'Heat'],
    MIL: ['Milwaukee Bucks', 'Bucks'],
    MIN: ['Minnesota Timberwolves', 'Timberwolves'],
    NOP: ['New Orleans Pelicans', 'Pelicans'],
    NYK: ['New York Knicks', 'Knicks'],
    OKC: ['Oklahoma City Thunder', 'Thunder'],
    ORL: ['Orlando Magic', 'Magic'],
    PHI: ['Philadelphia 76ers', '76ers'],
    PHO: ['Phoenix Suns', 'Suns'],
    POR: ['Portland Trail Blazers', 'Trail Blazers'],
    SAC: ['Sacramento Kings', 'Kings'],
    SAS: ['San Antonio Spurs', 'Spurs'],
    TOR: ['Toronto Raptors', 'Raptors'],
    UTA: ['Utah Jazz', 'Jazz'],
    WAS: ['Washington Wizards', 'Wizards'],
}

export { teamMapper, name_mapper, team_names}